GET http://localhost:8080/api/usuarios

###

GET http://localhost:8080/api/usuarios/3


###

GET http://localhost:8080/api/usuarios

###

POST http://localhost:8080/api/usuarios
Content-type: application/json

{
    "email": "turing@gmail.com",
    "senha": "senha3"
    
}

###

PUT http://localhost:8080/api/usuarios?id=8ee76c64-1f30-43e1-bb81-66a5c3323cfd  
Content-type: application/json

{
    "email": "Carlos@gamil.com",
    "senha": "algumasenhadois"
}

###

DELETE http://localhost:8080/api/usuarios?id=4


###

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "turing@gmail.com",
    "senha": "senha"
}