GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1


###
POST http://localhost:8080/api/posts
Content-Type : application/json

{
    "titulo" :   "Programando em JS Backend",
    "texto" : "Título do texto...",
    "userId": 90
}

###

PUT http://localhost:8080/api/posts?id=1
Content-Type: application/json

{
    "titulo": "Novo titulo",
    "texto": "Novo texto"
}

###

DELETE http://localhost:8080/api/posts?id=1